// export const ARTIST_DETAILS_REQUEST = 'ARTIST_DETAILS_REQUEST';
// export const ARTIST_DETAILS_SUCCESS = 'ARTIST_DETAILS_SUCCESS';
// export const ARTIST_DETAILS_FAIL = 'ARTIST_DETAILS_FAIL';

export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
export const ARTIST_LIST_FAIL = 'ARTIST_LIST_FAIL';
export const ARTIST_LIST_RESET = 'ARTIST_LIST_RESET';

export const ARTIST_BY_ID_REQUEST = 'ARTIST_BY_ID_REQUEST';
export const ARTIST_BY_ID_SUCCESS = 'ARTIST_BY_ID_SUCCESS';
export const ARTIST_BY_ID_FAIL = 'ARTIST_BY_ID_FAIL';
export const ARTIST_BY_ID_RESET = 'ARTIST_BY_ID_RESET';

export const ARTIST_GALLERY_ADDRESS_UPDATE_REQUEST =
  ' ARTIST_GALLERY_ADDRESS_REQUEST';
export const ARTIST_GALLERY_ADDRESS_UPDATE_SUCCESS =
  ' ARTIST_GALLERY_ADDRESS_SUCCESS';
export const ARTIST_GALLERY_ADDRESS_UPDATE_FAIL =
  ' ARTIST_GALLERY_ADDRESS_FAIL';
