export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const ARTWORK_LIST_REQUEST = 'ARTWORK_LIST_REQUEST';
export const ARTWORK_LIST_SUCCESS = 'ARTWORK_LIST_SUCCESS';
export const ARTWORK_LIST_FAIL = 'ARTWORK_LIST_FAIL';
export const ARTWORK_LIST_RESET = 'ARTWORK_LIST_RESET';

export const ARTWORK_DETAILS_REQUEST = 'ARTWORK_DETAILS_REQUEST';
export const ARTWORK_DETAILS_SUCCESS = 'ARTWORK_DETAILS_SUCCESS';
export const ARTWORK_DETAILS_FAIL = 'ARTWORK_DETAILS_FAIL';
export const ARTWORK_DETAILS_RESET = 'ARTWORK_DETAILS_RESET';

export const ARTWORK_DELETE_REQUEST = 'ARTWORK_DELETE_REQUEST';
export const ARTWORK_DELETE_SUCCESS = 'ARTWORK_DELETE_SUCCESS';
export const ARTWORK_DELETE_FAIL = 'ARTWORK_DELETE_FAIL';
export const ARTWORK_DELETE_RESET = 'ARTWORK_DELETE_RESET';

export const ARTWORK_VOUCHER_DELETE_REQUEST = 'ARTWORK_VOUCHER_DELETE_REQUEST';
export const ARTWORK_VOUCHER_DELETE_SUCCESS = 'ARTWORK_VOUCHER_DELETE_SUCCESS';
export const ARTWORK_VOUCHER_DELETE_FAIL = 'ARTWORK_VOUCHER_DELETE_FAIL';
export const ARTWORK_VOUCHER_DELETE_RESET = 'ARTWORK_VOUCHER_DELETE_RESET';

export const ARTWORK_UPDATE_REQUEST = 'ARTWORK_UPDATE_REQUEST';
export const ARTWORK_UPDATE_SUCCESS = 'ARTWORK_UPDATE_SUCCESS';
export const ARTWORK_UPDATE_FAIL = 'ARTWORK_UPDATE_FAIL';
export const ARTWORK_UPDATE_RESET = 'ARTWORK_UPDATE_RESET';

export const ARTWORK_CREATE_REQUEST = 'ARTWORK_CREATE_REQUEST';
export const ARTWORK_CREATE_SUCCESS = 'ARTWORK_CREATE_SUCCESS';
export const ARTWORK_CREATE_FAIL = 'ARTWORK_CREATE_FAIL';
export const ARTWORK_CREATE_RESET = 'ARTWORK_CREATE_RESET';

export const ARTWORK_SEARCH_REQUEST = 'ARTWORK_SEARCH_REQUEST';
export const ARTWORK_SEARCH_SUCCESS = 'ARTWORK_SEARCH_SUCCESS';
export const ARTWORK_SEARCH_FAIL = 'ARTWORK_SEARCH_FAIL';
export const ARTWORK_SEARCH_RESET = 'ARTWORK_SEARCH_RESET';
