export const FILTER_BY_REGION_REQUEST = 'FILTER_BY_REGION_REQUEST';
export const FILTER_BY_REGION_SUCCESS = 'FILTER_BY_REGION_SUCCESS';
export const FILTER_BY_REGION_FAIL = 'FILTER_BY_REGION_FAIL';
export const FILTER_BY_REGION_RESET = 'FILTER_BY_REGION_RESET';
